<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HistogramOpenFilterSecondvalue_Field</name>
   <tag></tag>
   <elementGuidId>719c54aa-a91b-4f5c-9510-efccf5dfd620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='popover-content']/div/div/div/div/div/span/input)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>70</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numeric-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover&quot;)/div[@class=&quot;popover-content&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-offset-2&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;input-group&quot;]/input[@class=&quot;form-control numeric-input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
