<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Sanity Tests for the ESP System</description>
   <name>ESPBasicSanity</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-04-30T16:07:18</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>27a45d69-102a-4eab-a6ed-2d145810b034</testSuiteGuid>
   <testCaseLink>
      <guid>0410dcad-726c-460d-a6d3-bc2c4e4c2120</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DeleteATPOrders</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9894c434-2ddc-45fc-a76d-781a5c07fe30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminGUISanity</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fe8ca893-d468-4cea-be82-8483222bfa54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DavidsonQueryTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b3d9343-c82b-4f42-b03b-785b88d3297c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f7ddff-330d-4343-803b-cb9483ee48ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06465a0-524a-4c84-9209-9c8fdb322bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0804181-df4c-4efe-b56a-00ed74f0399b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreviewSanity</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ade06f26-06c2-4ce1-862c-1b053119a01f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrderHistorySanityTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>223dafc9-f084-4e88-8ffd-e9ffc1490842</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landsat8AndOrthosOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1f8373-b4cb-4ea2-b9dd-683b1481c675</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee1a239-85d4-4f14-a856-d328228e60d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d6f444-302f-4e21-b470-20aa1febc1d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>699a7103-04df-4def-a304-242d8a367653</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LidarPostProcessing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63b6488b-675a-4194-87bc-b384beb5593f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43c30a86-ecc9-4134-891b-8779d560ff1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1fb712-fffd-4f8f-a199-6ca476d982d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43cc8002-a4e9-4132-a307-e6699ba5bb51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NAIPFilteredOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d785c840-1d00-4ce5-8366-0833a91858ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35eb19cf-bb71-428e-a4c6-7814e6caa3e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>654c5b5b-9e23-439e-b670-fb7afb88e674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c3d3183-004d-47dc-a544-3039da7d9afe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SmokeTest01</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fdc6fc1a-d4a8-465b-be7b-f07f4e1411c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landsat8AndNAIPOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c7d504a-237d-4291-8819-703614ae5ca9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1674f07-7185-4d1c-8b4e-6d5b3c9b5f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>027a7cd0-2127-4b59-897d-79d8a7f42372</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
