<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-09T15:27:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c8a9929a-398a-46d3-9fd0-3be3cb9b4a4d</testSuiteGuid>
   <testCaseLink>
      <guid>8ce2ac0e-91a3-4664-bb28-7097c9770bf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landsat8AndNAIPOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c7d504a-237d-4291-8819-703614ae5ca9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1674f07-7185-4d1c-8b4e-6d5b3c9b5f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>027a7cd0-2127-4b59-897d-79d8a7f42372</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05264cf4-c834-42ca-a69d-ca7a3e24f160</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landsat8AndOrthosOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1f8373-b4cb-4ea2-b9dd-683b1481c675</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee1a239-85d4-4f14-a856-d328228e60d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d6f444-302f-4e21-b470-20aa1febc1d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b51d3fd-8232-4b8f-b0eb-302ebe9ab797</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LidarandOrthosOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>684e8664-c239-4252-a8dd-8379a3adbbda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0be5fd5-8c80-463e-a57e-2ac58234af6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2544bbd2-71d7-4fb0-a350-4519e14d698e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d3bd065-6d78-48f2-8dd0-91321c6b3732</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LidarPostProcessing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63b6488b-675a-4194-87bc-b384beb5593f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43c30a86-ecc9-4134-891b-8779d560ff1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1fb712-fffd-4f8f-a199-6ca476d982d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fe9dabe-ee08-4946-9bdd-8dbe0256b23f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NAIPFilteredOrder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d785c840-1d00-4ce5-8366-0833a91858ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35eb19cf-bb71-428e-a4c6-7814e6caa3e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>654c5b5b-9e23-439e-b670-fb7afb88e674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bb4f580-751b-413a-a416-036929ece49e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrderHistoryAddToCart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a5ca43c6-0bc2-4693-89b3-c760d2e0c899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrderHistorySanityTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7be0932d-906c-481c-a825-2fe9255f80a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreviewSanity</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d993dc28-b397-4add-9f7e-43502ec9f7f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SearchResultsSanity</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ba468699-b86d-4a6e-9b55-c3017b99435b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SmokeTest01</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
