<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AOIClearAOI_Button</name>
   <tag></tag>
   <elementGuidId>072889db-0dc8-4b99-99c9-12c734044b4e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-window-close cesium-button cesium-toolbar-button btn btn-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;tb-wrapper tb-slide-in&quot;]/div[@class=&quot;tb-vertical-slidingcontainer&quot;]/div[@class=&quot;tb-vertical&quot;]/div[@class=&quot;btn-group-container&quot;]/div[@class=&quot;btn-group-row&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;far fa-window-close cesium-button cesium-toolbar-button btn btn-primary&quot;]</value>
   </webElementProperties>
</WebElementEntity>
