<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderDetails_XButton</name>
   <tag></tag>
   <elementGuidId>77cd72bf-6fe6-4a71-a18d-cec4cdefe844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-history']/span/div[contains(@class,'react-draggable')]/descendant::i[contains(@class,'fa-times')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-history&quot;)/span[1]/div[@class=&quot;draggable-panel react-draggable react-draggable-dragged panel panel-primary&quot;]/div[@class=&quot;panel-heading&quot;]/span[@class=&quot;panel-title&quot;]/a[1]/button[@class=&quot;close btn btn-default&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
   </webElementProperties>
</WebElementEntity>
