<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Users</name>
   <tag></tag>
   <elementGuidId>a1e9a858-8306-41e5-a8e7-7f9b1704f5d8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;page-wrapper&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-6&quot;]/div[@class=&quot;panel-primary panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/div[@class=&quot;row panel-title&quot;]/div[@class=&quot;col-xs-9 text-right&quot;]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
