<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttributeFilterAttributeNameDropdown</name>
   <tag></tag>
   <elementGuidId>09b45fed-5794-4519-b615-b8d768887fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select[(contains(@class,'filterAttributeSelect'))])[ROWNDX]/option[(text()='ATTNAME')]</value>
   </webElementProperties>
</WebElementEntity>
