<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttributeFilterOperator</name>
   <tag></tag>
   <elementGuidId>9e8d33bf-9203-43bf-91d7-1656655560e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//select[(contains(@class,'operator'))])[ROWNDX]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[(contains(@class,'operator'))])[ROWNDX]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select[(contains(@class,'operator'))])[ROWNDX]</value>
   </webElementProperties>
</WebElementEntity>
