<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UnCoveredAreaRow1AddToCart</name>
   <tag></tag>
   <elementGuidId>793c5e98-5000-4dcd-903b-fd6d3ae46ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult-pane-2']/descendant::div[@class='fixedDataTableRowLayout_rowWrapper'][2]/descendant::i[contains(@class,'fa-cart-plus')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
