<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NamedSearch_SelectField</name>
   <tag></tag>
   <elementGuidId>6cd11710-d2d0-4bc4-a1af-6ebb843f0c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name=&quot;namedSearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namedSearch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formNamedSearch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ...221DavisionNamedSearchTest221testRuiAM-AcsRestrictionAM-LSAcsRstrAM_SanityTest2ANamedSearchBag-Csar-Hari-TestingDavidson NS testDavidsonNorthLidar_FunctionalTest_NO_DELETEdesertsearchDESIS30FileHoustonOrthosHoustonOrthos_FunctionalTest_DO_NOT_DELETEL1A_Naip_NDVI no AOIl2a production testNamed-Search-TestingOrthos&amp;LIDARNoAOIOrthos&amp;Lidar_No_AOI_FunctionalTest_NO_DELETEPalmBeachLIDARPaloAltoLandsatPensacola LidarRefugioLidar_FunctionalTest_DO_NOT_DELETERefugioOrthosSmokeTest01</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formNamedSearch&quot;)</value>
   </webElementProperties>
</WebElementEntity>
