<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ColumnFilter</name>
   <tag></tag>
   <elementGuidId>02dddfce-4398-4470-bd06-1c31577790da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[(text()='COLNAME')]/parent::a/following-sibling::span/i</value>
   </webElementProperties>
</WebElementEntity>
