<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GridRowFunctions</name>
   <tag></tag>
   <elementGuidId>c89b516e-5393-4a29-a48f-3eb82fab0de0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='fixedDataTableRowLayout_rowWrapper'][ROWNDX]/descendant::i[contains(@class,'CLASS')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='fixedDataTableRowLayout_rowWrapper'][1]/descendant::i[@class='CLASS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='fixedDataTableRowLayout_rowWrapper'][ROWNDX]/descendant::i[contains(@class,'CLASS')]</value>
   </webElementProperties>
</WebElementEntity>
