<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProjectItemsSelectAll</name>
   <tag></tag>
   <elementGuidId>aa47e3c2-ee7a-4796-b431-465feb769d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='fixedDataTableCellGroupLayout_cellGroup']/div[@class='fixedDataTableCellLayout_main public_fixedDataTableCell_main'])[1]/descendant::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;project-item-grid-container&quot;]/div[@class=&quot;draggable-panel react-draggable panel panel-primary&quot;]/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body&quot;]/span[1]/div[@id=&quot;genericGridContainer&quot;]/div[@class=&quot;table-responsive grid-min-height&quot;]/table[@class=&quot;table-striped table-bordered custom-grid project-item-grid-hover-style&quot;]/thead[1]/tr[@class=&quot;grid-header-row fit&quot;]/th[@class=&quot;project-item-grid-th-background&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
