<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResultsField_Displaying</name>
   <tag></tag>
   <elementGuidId>65de6e49-05d9-45a5-a88c-6f80b3103987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult-pane-1']/descendant::b[(contains(text(),'Displaying'))]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//b[(text() = 'Displaying 486 of 486 Item(s) ' or . = 'Displaying 486 of 486 Item(s) ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Displaying 486 of 486 Item(s) </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult-pane-1&quot;)/div[@class=&quot;search-result-product-grid&quot;]/div[@id=&quot;genericGridContainer&quot;]/div[2]/b[1]</value>
   </webElementProperties>
</WebElementEntity>
