<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResults_SelectAll</name>
   <tag></tag>
   <elementGuidId>202cb411-f02b-4bdd-a077-71d69a434bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;searchResult-pane-1&quot;)/div[@class=&quot;search-result-product-grid&quot;]/div[@id=&quot;genericGridContainer&quot;]/div[@class=&quot;table-responsive grid-min-height&quot;]/table[@class=&quot;table-striped table-bordered custom-grid search-result-hover-style&quot;]/thead[1]/tr[@class=&quot;grid-header-row fit&quot;]/th[@class=&quot;search-result-th-background&quot;]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult-pane-1&quot;)/div[@class=&quot;search-result-product-grid&quot;]/div[@id=&quot;genericGridContainer&quot;]/div[@class=&quot;table-responsive grid-min-height&quot;]/table[@class=&quot;table-striped table-bordered custom-grid search-result-hover-style&quot;]/thead[1]/tr[@class=&quot;grid-header-row fit&quot;]/th[@class=&quot;search-result-th-background&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
