<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderHistory_Row1SelectBox</name>
   <tag></tag>
   <elementGuidId>58bfaf25-abf5-4077-829f-9d707bb68178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(id(&quot;genericGridContainer&quot;)/div[@class=&quot;table-responsive grid-min-height&quot;]/table[@class=&quot;table-striped table-bordered custom-grid order-history-hover-style&quot;]/tbody[1]/tr[@class=&quot;grid-body-row fit&quot;]/td/input)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genericGridContainer&quot;)/div[@class=&quot;table-responsive grid-min-height&quot;]/table[@class=&quot;table-striped table-bordered custom-grid order-history-hover-style&quot;]/tbody[1]/tr[@class=&quot;grid-body-row fit&quot;]/td[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
