<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UsersEmailFilter_Button</name>
   <tag></tag>
   <elementGuidId>c200b327-0d9d-4b96-8e6b-0902261679ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead/descendant::span[(text()='Email')]/parent::a/parent::div/descendant::i[(contains(@class,'filter'))]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
