<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UsersEmailFilter_Field</name>
   <tag></tag>
   <elementGuidId>c07901eb-ab5b-4517-9664-5be048c508ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead/tr/th/div/a/span[(text()='Email')]/../../div/div/ul/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
