<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateProjectSelectProjectTypeLidar</name>
   <tag></tag>
   <elementGuidId>723759fc-b5f2-4ab1-a528-b1b0c145edbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[(text()='Lidar')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
