<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProjectFilterAttributeName_Dropdown</name>
   <tag></tag>
   <elementGuidId>c04d5539-38be-4279-b89a-0bfa544b24ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[(contains(@class,'filterAttributeSelect'))]/option[(text()='Name')]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
