<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessageRightSideFirstCheckbox</name>
   <tag></tag>
   <elementGuidId>c9c701e8-e384-4248-be41-05b2307b9d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(contains(@class,'bidirectional-grid-right'))]/div[@class='container-fluid']/descendant::div[@class='public_fixedDataTableCell_cellContent']/input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
