<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SystemInfoTableContainer</name>
   <tag></tag>
   <elementGuidId>1c76d8c6-9315-4a1f-aa9f-f7862cf0a3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(contains(@id, 'tabs-pane-1'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genericGridContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-fluid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company NameOrganization NameUser NameOrder NameItemsSubmittedCompletedStatusCompany Name LikeOrganization Name LikeUser Name LikeOrder Name LikeItems ≥ ≤ =Submitted ≥ ≤ =Status  Select AllCREATEDSTARTEDSUBMITTEDSUCCESSFAILUREWARNINGCANCELEDREJECTED   GeoCue  GeoCue  dglenn@geocue.com  ATPLSandNAIP-2018-05-30 11:12:39  2  5/30/2018  SUCCESS    GeoCue  GeoCue  dglenn@geocue.com  ATPLSandOrthoOrder-2018-05-30 11:13:19  2  5/30/2018  SUCCESS Displaying 2 of 278 Item(s) </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genericGridContainer&quot;)</value>
   </webElementProperties>
</WebElementEntity>
