<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReportsOrderReportOrganization</name>
   <tag></tag>
   <elementGuidId>08d048bf-cef8-41cc-842d-cd8841d87e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sysinfo-tabs-pane-1']/div/div/form/div/div/div/div/select[@placeholder='Organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Organization  Airgon TestOnly  Airgon TestOnly1  GeoCue  new </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sysinfo-tabs-pane-1&quot;)/div[@class=&quot;reportPanel panel panel-primary&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;reportForm&quot;]/div[1]/div[@class=&quot;taskingFormGroup form-group has-feedback has-error&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/select[@class=&quot;form-control&quot;]</value>
   </webElementProperties>
</WebElementEntity>
