<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalibrationRequestEarliestDate</name>
   <tag></tag>
   <elementGuidId>31d1158a-cc84-4e93-aed7-19087d432f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@class='limitTaskingParameters']/descendant::input[@placeholder='Earliest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Earliest</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datePick</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/span[@class=&quot;tasking-parameters-container&quot;]/div[@class=&quot;react-draggable&quot;]/div[@class=&quot;draggable-panel panel panel-primary&quot;]/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body&quot;]/span[1]/div[@class=&quot;row&quot;]/form[@class=&quot;limitTaskingParameters&quot;]/div[@class=&quot;taskingFormGroup form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;form-control datePick&quot;]</value>
   </webElementProperties>
</WebElementEntity>
