<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalibrationRequestRecurrence</name>
   <tag></tag>
   <elementGuidId>7fb54ee1-f66e-4d30-bca4-4d80a03420a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[(text()='Interval')]/parent::select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1536961298181</value>
   </webElementProperties>
</WebElementEntity>
