<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttributeFilterAttributeName_Dropdown</name>
   <tag></tag>
   <elementGuidId>3a7c6779-040c-47ca-a6ba-17e8820f3adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//select[(contains(@class,'filterAttributeSelect'))])[ROWNDX]/option[(text()='ATTNAME')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[(contains(@class,'filterAttributeSelect'))])[ROWNDX]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select[(contains(@class,'filterAttributeSelect'))])[ROWNDX]/option[(text()='ATTNAME')]</value>
   </webElementProperties>
</WebElementEntity>
