<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttributeFilterDateValue_Field</name>
   <tag></tag>
   <elementGuidId>2b716f18-9dbf-44f8-82eb-7c1415b3f08b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[(contains(@class,'datePick'))])[ROWNDX]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[(contains(@class,'datePick'))])[ROWNDX]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[(contains(@class,'datePick'))])[ROWNDX]</value>
   </webElementProperties>
</WebElementEntity>
