<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductSelectionNAIPNDVI_CheckBox</name>
   <tag></tag>
   <elementGuidId>41ab0189-836b-4a82-840b-3c5e86cdc3f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'NAIP')]/parent::td/parent::tr/following-sibling::tr/td/span[(text()='NDVI')]/parent::td/preceding-sibling::td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[6]/span[1]/div[@class=&quot;prodSelection&quot;]/div[@class=&quot;field&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[2]/td[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
