<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductSelectionAnyCheckbox</name>
   <tag></tag>
   <elementGuidId>a40a6d7e-db4c-4d22-86d4-f83bbc34d680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//td/input[@type='checkbox'])[CHKNDX]</value>
   </webElementProperties>
</WebElementEntity>
