<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrganizationNameFilterButton</name>
   <tag></tag>
   <elementGuidId>44602ee3-4d37-463d-a8c1-304306de7c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead/descendant::span[(text()='Name')]/parent::a/parent::div/descendant::i[(contains(@class,'filter'))]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//thead/descendant::span[(text()='Name')]/parent::a/parent::div/descendant::i[(contains(@class,'filter'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-filter header-icon-size</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead/descendant::span[(text()='Name')]/parent::a/parent::div/descendant::i[(contains(@class,'filter'))]</value>
   </webElementProperties>
</WebElementEntity>
