<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrthoLoaderSelectATPProject</name>
   <tag></tag>
   <elementGuidId>192adec2-edb7-4616-97cb-c9090905dd28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[(text()='ATPOrthoProject')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'frmProject' and (text() = 'Select ProjectOrthoTesttest orth with footprintpascoOrthoLoaderTest May 1Ortho test 2 May 1Ortho with footprintortho test 3' or . = 'Select ProjectOrthoTesttest orth with footprintpascoOrthoLoaderTest May 1Ortho test 2 May 1Ortho with footprintortho test 3')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmProject</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box-input form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProjectOrthoTesttest orth with footprintpascoOrthoLoaderTest May 1Ortho test 2 May 1Ortho with footprintortho test 3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmProject&quot;)</value>
   </webElementProperties>
</WebElementEntity>
