<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HistogramShowHideFilters_button</name>
   <tag></tag>
   <elementGuidId>d87546c9-6fdc-4d2f-be46-1a53baf7c543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.fa-sliders-h</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'showHideFilter' and @type = 'button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='tb-wrapper advanced-menu tb-slide-in']//button[@class='fas fa-chart-bar cesium-button cesium-toolbar-button btn btn-primary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showHideFilter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cesium-button btn btn-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>showHideFilters</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showHideFilter&quot;)</value>
   </webElementProperties>
</WebElementEntity>
