<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe___ExpDate</name>
   <tag></tag>
   <elementGuidId>0230c286-8ed0-4819-94bd-b192b23326b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@name = '__privateStripeFrame5' and @src = 'https://js.stripe.com/v3/elements-inner-card-4a29888d5af683ac95fb41d7321c34e4.html#style[base][fontSize]=18px&amp;style[base][color]=%23424770&amp;style[base][letterSpacing]=0.025em&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%239e2146&amp;componentName=cardExpiry&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fgetlidar-alternate.com&amp;referrer=https%3A%2F%2Fgetlidar-alternate.com%2F&amp;controllerId=__privateStripeController1' and @title = 'Secure payment input frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowpaymentrequest</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-4a29888d5af683ac95fb41d7321c34e4.html#style[base][fontSize]=18px&amp;style[base][color]=%23424770&amp;style[base][letterSpacing]=0.025em&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%239e2146&amp;componentName=cardExpiry&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fgetlidar-alternate.com&amp;referrer=https%3A%2F%2Fgetlidar-alternate.com%2F&amp;controllerId=__privateStripeController1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;fade in modal&quot;]/div[@class=&quot;messagebox subscription modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;spacing-all&quot;]/div[@class=&quot;vdivide row&quot;]/div[@class=&quot;col-md-7 col-md-offset-1&quot;]/div[@class=&quot;Checkout&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;StripeElement StripeElement--empty StripeElement--focus&quot;]/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
   </webElementProperties>
</WebElementEntity>
