<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BasemapNamedSearchOption_ATPLidarNS</name>
   <tag></tag>
   <elementGuidId>fa92406b-f170-4ee2-8d8d-eafa8102b620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[(text()='ATPLidarNS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namedSearchId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basemapSourceSearch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...AM - issue # 6850AM-DeleteLaterAM-Issue-6850AM-NoDataAM6850ReplicationATPLidarNSDav north 76Davidson westDavidsonNorthLidar_FunctionalTest_NO_DELETEDavNarrowHari-No-Data-01Hari-NoDataissue 6850Las in DavidsonLidarInMadisonmy searchnamed-search-test-#12NE FL LidarOpryland SearchOpryland_HotelOpryland_Hotel_floodingPalmBeachLidar_FunctionalTest_DO_NOT_DELETEPRRefugioLidar_FunctionalTest_DO_NOT_DELETEtest davidsonTest-AshleyTestLandsatAirbornetest_opryland_demoWillistonWillistonLidar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basemapSourceSearch&quot;)</value>
   </webElementProperties>
</WebElementEntity>
