<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkingSetCountBadge</name>
   <tag></tag>
   <elementGuidId>5635067f-7792-4362-ba9d-92fcaa02c960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button [@class='fa fa-gavel cesium-button btn btn-primary']/span[@class='badge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;tb-wrapper tb-slide-in&quot;]/div[@class=&quot;tb-vertical-slidingcontainer&quot;]/div[@class=&quot;tb-vertical&quot;]/div[@class=&quot;btn-group-container&quot;]/div[@class=&quot;btn-group-row&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;fa fa-gavel cesium-button btn btn-primary&quot;]/span[@class=&quot;badge&quot;]</value>
   </webElementProperties>
</WebElementEntity>
