<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GridValue</name>
   <tag></tag>
   <elementGuidId>150bb41a-69c0-42b0-8e6e-087a543ed350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='searchResult-pane-1']/descendant::tbody/tr[ROWNDX]/td[COLNDX]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult-pane-1']/descendant::tbody/tr[1]/td[COLNDX]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='searchResult-pane-1']/descendant::tbody/tr[ROWNDX]/td[COLNDX]</value>
   </webElementProperties>
</WebElementEntity>
