<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResults_SelectFirstRow</name>
   <tag></tag>
   <elementGuidId>f58ac37f-1bc8-4005-983e-3e8facf22615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//div[@id='searchResult-pane-1']/descendant::div[@class='fixedDataTableRowLayout_rowWrapper'][2]/descendant::input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult-pane-1']/descendant::div[@class='fixedDataTableRowLayout_rowWrapper'][2]/descendant::input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
