<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchResultsClearAllFilters_Button</name>
   <tag></tag>
   <elementGuidId>408c84a6-8cb3-44db-b2a0-ff57d0e84375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id('searchResult-pane-1')/descendant::button[(contains(@class,'clear-all-grid-filter'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1531338699900</value>
   </webElementProperties>
</WebElementEntity>
